## RUN PARAMS

# MANDATORY PARAMS

# path to FASTA file of reference genome
# default = workflow/resources/pangenomeMTB_consensus.fasta
# genome_file: /path/to/reference_genome.fasta
genome_file: workflow/resources/pangenomeMTB_consensus.fasta

# path to BED file of reference genome gaps
# default = workflow/resources/pangenomeMTB_genome_gaps.bed
# genomegaps_file: /path/to/reference_genome_gaps.bed
genomegaps_file: workflow/resources/pangenomeMTB_genome_gaps.bed

# path to BED file of excluded reference genome locations regarding to the PE/PPE, PE-PGRS and drug-resistance associated genes
# default = workflow/resources/exclusion/pangenomeMTB_excluded_loci.bed
# exclude_regions_file: /path/to/reference_genome_excluded_loci.bed
exclude_regions_file: workflow/resources/exclusion/pangenomeMTB_excluded_loci.bed

# kraken v1 reference database.
# MiniKraken DB is suggested (https://ccb.jhu.edu/software/kraken/dl/minikraken_20171019_8GB.tgz).
# kraken_db: /path/to/minikraken_20171019_8GB
kraken_db: minikraken_20171019_8GB

# path to Text file including all samples information. One sample per line.
# The line should start with the "sample" column and contain at least a "date" column.
# For transmission network reconstruction, both "longitude" and "latitude" columns could be used.
# metadata_file: /path/to/samples.txt
metadata_file: examples/samples.txt

# PARAMS WITH DEFAULT VALUES

# path to directory with fastq files
# default 'fastq' in working directory
# fastqdir: /path/to/fastq/
fastqdir: fastq

# fastq files are assumed to be of the format sample_1.fastq.gz
# use "fastqpostfix" for different file name formats 
# e.g. for the format sample_R1.fastq.gz put fastqpostfix: R

# The ids of all fastq files in the directory can be matched with glob patterns. Otherwise, only ids in the metadata file will be parsed.
# default = false
glob_files: false

# threads used by tools for each sample
sample_threads: 1

## Filter params
# the quality value that a base is qualified. Default 15 means phred quality >=Q15 is qualified.
base_quality: 15

# minimum allele frequency to be considered 'homozygous' variant call
# default = 0.75
allele_frequency_threshold: 0.75

# minimum mapping quality for reads to be used for variant calling
# default = 10
mapping_quality_threshold: 10

# minimum GATK depth (DP) value to be considered valid variant call
# default = 10
depth_threshold: 10

## Tool params
# minimum overlap of paired end reads for merging
# default = 10
flash_overlap: 10

# minimum length of reads to be kept with trimmomatic
# default = 50
trimmomatic_read_minimum_length: 50

# quality for sliding window trimmomatic trimming. default value is 15 according to Trimmomatic manual.
# default = 15
# trimmomatic_qual_slidingwindow: 
trimmomatic_qual_slidingwindow: 15

# cutoff for MTBC sequences percentage. 
kraken_cutoff: 90

# filtering out non-MTBC reads with kraken. That would allow for contaminated samples to still be reliably processed.
# Default is false
MTBC_reads_only: false

# output files prefix
output_prefix: samples

# fontsize for all rownames and colnames
# default is null then the pipeline will auto adjust font size in pheatmap.
heatmap_font_size: null

# transmission clustering method. Both [SNP] and [trans] methods are supported.
# default = trans
method: SNP

# parameters for SNP-based clustering: check transmission validity.
# agglomerative single-linkage clustering is valid based on similarity but not in the context of epidemiological transmission analysis
# if check_transmission_validity is true, merging of distant samples by a "proxy" sample is detected and excluded.
# clustering is repeated without those "proxy" samples until no such samples are detected any more.
# default = true
check_transmission_validity: true

# parameters for SNP-based clustering: SNP threshold
# default = 12
snp_threshold: 12

# transmission threshold is the threshold under which the estimated number of intermediate transmissions must be in order for two cases to be defined as clustered.
# default = 15
transmission_threshold: 15

# clock rate. 
# default = 0.5 SNPs/genome/year
clock_rate: 0.5

# transmission rate is the rate at which the estimated number of intermediate transmissions must be.
# default = 2.0
transmission_rate: 2.0

# using coordinate to reconstruct transmission network.
coordinate: true

# epidemiological characteristics
characteristics: 
